#!/bin/bash

set -eux

# For latest boost
# bionic-18.04 is at boost 1.65 and doesn't have asio dispatch (introduced in 1.66)
sudo add-apt-repository ppa:mhier/libboost-latest
sudo apt-get update

apt-get -y install build-essential git wget libclang-dev libgl1-mesa-dev ninja-build libboost1.70-dev xorg-dev libdbus-1-dev libssl-dev ca-certificates tzdata
