#!/bin/bash

set -eux

RUSTUP_URL="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
RUSTUP_HOME=${RUSTUP_HOME:-/usr/local/rustup}
CARGO_HOME=${CARGO_HOME:-/usr/local/cargo}

wget "$RUSTUP_URL"
chmod +x rustup-init
./rustup-init -y --no-modify-path --default-toolchain nightly
rm rustup-init

if [ ! -z "${GITHUB_PATH-}" ]; then
  echo "$CARGO_HOME/bin" >>$GITHUB_PATH
  echo "$RUSTUP_HOME/bin" >>$GITHUB_PATH
fi
PATH="$PATH:$CARGO_HOME/bin:$RUSTUP_HOME/bin"

rustup --version
cargo --version
rustc --version
