#!/bin/bash

set -eux

# Github CI image already has rust
if [ -z "${GITHUB_ACTION-}" ]; then
  RUSTUP_URL="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
  RUSTUP_HOME=${RUSTUP_HOME:-/usr/local/rustup}
  CARGO_HOME=${CARGO_HOME:-/usr/local/cargo}

  wget "$RUSTUP_URL"
  chmod +x rustup-init
  ./rustup-init -y --no-modify-path --default-toolchain nightly
  rm rustup-init
  
  PATH="$PATH:$CARGO_HOME/bin:$RUSTUP_HOME/bin"
fi

rustup toolchain install nightly
rustup target add wasm32-unknown-emscripten
rustup update

rustup --version
cargo --version
rustc --version
