if(X86 AND NOT EMSCRIPTEN)
  if(FORCE_CORE2)
    set(RUST_ARCH "-Ctarget-cpu=core2 ")
  elseif(FORCE_I686)
    set(RUST_ARCH "-Ctarget-cpu=i686 ")
  elseif(FORCE_NATIVE)
    set(RUST_ARCH "-Ctarget-cpu=native ")
  else()
    set(RUST_ARCH "-Ctarget-cpu=sandybridge ")
  endif()
endif()