name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      RUSTUP_HOME: ~/.rustup
      CARGO_HOME: ~/.cargo
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo scripts/linux/install_packages
        scripts/linux/install_rust
    - name: Configure
      run: scripts/linux/configure
    - name: Build
      run: scripts/linux/build
    - name: Build
      run: scripts/linux/test
