name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup
      run: |
        sudo bash scripts/linux/install_packages
        bash scripts/linux/install_rust
    - name: Configure
      run: bash scripts/linux/configure
    - name: Build
      run: bash scripts/linux/build
    - name: Test
      run: bash scripts/linux/test
    - uses: actions/upload-artifact@master
      with:
        name: cbl
        path: |
          build/bin/cbl
